
/*
Even Fibonacci Numbers
Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million,
find the sum of the even-valued terms.
LINK DO PROBLEMA - https://projecteuler.net/problem=2
 */

/**
 *
 * @author mateus
 */
public class Even_Fibonacci_Numbers {
    public static void main(String[] args) {
       
    int soma = 2; //Começa em dois pois é o primeiro número par da sequência.
    int termo1 = 2;
    int termo2 = 3; //Começa nos números 2 e 3, pois a primeiro soma de resultado par já está colocada na soma. 
    int termo;
    do{
        termo = termo1+termo2;  //Seguinte termo = dois últimos termos da sequência. 
        termo1 = termo2;
        termo2 = termo; //O que era o termo 2 torna-se o termo 1 e o seguinte número que foi descoberto torna-se o termo 2. 
        
        if(termo%2==0){ // Ou seja, se o termo for par.
            soma = soma+termo; //Soma o termo ao resultado da soma dos termos pares da sequência. 
             }
        System.out.println(soma); //Imprime no monitor o resultado final da soma. 

    }while(termo<=4000000); //Enquanto o termo não exceda o número de 4 milhões. 
    
    }
       
}
